tasks:
  - command: yarn run watch
    init: yarn install && yarn run build
  - command: run npm install 
    init: npm install
  - command: run cdk install
    init: npm install -g aws-cdk
  - command: install tree 
    init: sudo apt install tree
  - name: Initialize & Configure AWS
    command: bash $GITPOD_REPO_ROOT/gitpod_scripts/gitpod_configure_aws.sh
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - AmazonWebServices.aws-toolkit-vscode