tasks:
  # - name: yarn run watch
  #   init: |
  #     yarn install 
  #     yarn run build
  #   command: yarn run watch
  - name: Initialize & Configure AWS
    command: bash $GITPOD_REPO_ROOT/gitpod_scripts/gitpod_configure_aws.sh
  - name: Install DOTNET 6.0
    command: bash $GITPOD_REPO_ROOT/gitpod_scripts/gitpod_configure_dotnet.sh
  - name: run npm install
    init: npm install 
  - name: install tree
    init: sudo apt install tree 
  - name: install cdk
    init: npm install -g aws-cdk
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - AmazonWebServices.aws-toolkit-vscode